name = "highflybetcasino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=highflybetcasino.com.pt"
HMAC_KEY = "87e02cb880e7baa0c8e8577d508d73846676befbc8524ab8f716f07269691514"
COOKIE_NAME = "zle"
PLAY_PATH = "start"
BUTTON_ID = "pf205a8cacde3bbc75be44430a1f06748"
GATE_SALT = "c93eae411cc95dfa"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ddrl"
CTA_SELECTOR = ".play-button"
