name = "highflybetcasino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=highflybetcasino.com.pt"
HMAC_KEY = "87e02cb880e7baa0c8e8577d508d73846676befbc8524ab8f716f07269691514"
COOKIE_NAME = "ebp"
PLAY_PATH = "play"
BUTTON_ID = "pf205a8cacde3bbc75be44430a1f06748"
GATE_SALT = "9a34f87f9a1e9c80"
